#!/usr/bin/env sh

im="eclipse-mosquitto"

# shellcheck disable=SC1090
. "$(dirname "$0")/reg-tags/image_tags.sh"

for tag in $(img_tags --filter '[0-9]+(\.[0-9]+)+$' --verbose -- "$im"); do
    if docker image inspect "${DOCKER_REPO}:$tag" >/dev/null 2>&1; then
        echo "============== Pushing ${DOCKER_REPO}:$tag"
        docker push "${DOCKER_REPO}:$tag"
    else
        echo "!!!!!!!!!!!!!! ${DOCKER_REPO}:$tag was not built, cannot push!"
    fi
done
